# Generated by Django 5.1.7 on 2025-03-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="phone",
            field=models.PositiveIntegerField(max_length=15),
        ),
    ]
